INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 1, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 1, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 2, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 2, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 3, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 6);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 7);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 8);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 4, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 4, 10);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 6);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 8);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 5, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 5, 10);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 6, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 7, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 7, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 7, 6);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 8, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 8, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 8, 6);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 8, 10);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 9, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 9, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 9, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 10, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 10, 3);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 10, 10);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 11, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 12, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 12, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 12, 6);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 12, 7);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 13, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 13, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 13, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 13, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 13, 5);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 13, 10);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 14, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 14, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 14, 6);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 15, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 15, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 15, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 15, 8);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 16, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 16, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 16, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 17, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 17, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 18, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 18, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 19, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 19, 2);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 20, 1);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 20, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 21, 1);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 21, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 22, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 22, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 22, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 23, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 24, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 24, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 24, 4);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 24, 8);	

INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 24, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 25, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 25, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 25, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 25, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 25, 6);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 25, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 25, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 26, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 27, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 27, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 27, 6);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 27, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 28, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 29, 5);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 30, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 30, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 30, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 31, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 31, 2);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 32, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 32, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 32, 6);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 32, 8);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 33, 1);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 33, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 33, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 33, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 34, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 34, 6);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 35, 1);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 35, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 35, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 35, 8);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 36, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 36, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 36, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 36, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 36, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 36, 6);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 36, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 6);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 7);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 8);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 37, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 37, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 38, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 38, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 38, 4);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 39, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 39, 6);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 39, 8);	

INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 39, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 40, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 41, 6);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 41, 8);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 42, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 42, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 42, 6);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 43, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 44, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 44, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 45, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 45, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 46, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 46, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 47, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 47, 4);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 48, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 48, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 48, 4);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 48, 6);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 48, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 49, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 49, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 49, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 50, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 50, 6);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 50, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 51, 2);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 51, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 52, 5);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 53, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 53, 4);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 54, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 54, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 54, 6);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 54, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 55, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 55, 2);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 56, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 56, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 56, 4);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 56, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 57, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 57, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 57, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 58, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 59, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 59, 3);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 59, 4);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 59, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 59, 6);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 59, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 59, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 60, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 60, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 61, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 61, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 62, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 63, 5);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 64, 1);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 64, 2);
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 64, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 65, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 65, 7);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 65, 8);	

INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 65, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 66, 5);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 66, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 66, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 67, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 67, 10);
	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 68, 2);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 68, 3);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 69, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 70, 2);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 70, 4);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 71, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 71, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 71, 5);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 71, 6);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 71, 8);	

INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 71, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 72, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 72, 8);	
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 72, 9);	
INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 72, 10);

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 73, 1);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 74, 5);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 75, 1);	

INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 75, 3);
INSERT INTO tbl_cupo VALUES (null, 2, 2, CURRENT_DATE, CURRENT_DATE, 75, 8);	

INSERT INTO tbl_cupo VALUES (null, 1, 1, CURRENT_DATE, CURRENT_DATE, 75, 10);