INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 1, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 1, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 2, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 2, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 3, 1);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 7);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 8);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 4, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 4, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 8);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 5, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 5, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 6, 1);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 7, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 7, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 7, 6);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 8, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 8, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 8, 6);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 8, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 9, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 9, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 9, 4);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 10, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 10, 3);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 10, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 11, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 12, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 12, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 12, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 12, 7);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 13, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 13, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 13, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 13, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 13, 5);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 13, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 14, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 14, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 14, 6);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 15, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 15, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 15, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 15, 8);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 16, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 16, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 16, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 17, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 17, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 18, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 18, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 19, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 19, 2);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 20, 1);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 20, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 21, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 21, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 22, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 22, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 22, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 23, 2);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 24, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 24, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 24, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 24, 8);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 24, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 25, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 25, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 25, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 25, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 25, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 25, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 25, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 26, 2);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 27, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 27, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 27, 6);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 27, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 28, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 29, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 30, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 30, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 30, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 31, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 31, 2);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 32, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 32, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 32, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 32, 8);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 33, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 33, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 33, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 33, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 34, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 34, 6);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 35, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 35, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 35, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 36, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 36, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 36, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 36, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 36, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 36, 6);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 36, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 7);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 8);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 37, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 37, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 38, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 38, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 38, 4);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 39, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 39, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 39, 8);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 39, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 40, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 40, 8);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 41, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 41, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 41, 6);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 42, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 43, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 43, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 44, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 44, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 45, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 45, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 46, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 46, 4);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 47, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 47, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 47, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 47, 6);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 47, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 48, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 48, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 48, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 49, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 49, 6);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 49, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 50, 2);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 50, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 51, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 52, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 52, 4);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 53, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 53, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 53, 6);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 53, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 54, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 54, 2);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 55, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 55, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 55, 4);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 55, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 56, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 56, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 56, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 57, 2);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 58, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 58, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 58, 4);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 58, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 58, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 58, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 58, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 59, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 59, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 60, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 60, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 61, 5);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 62, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 62, 2);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 62, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 63, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 63, 7);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 63, 8);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 63, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 64, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 64, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 64, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 65, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 65, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 66, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 66, 3);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 67, 1);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 68, 2);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 68, 4);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 69, 1);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 69, 3);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 69, 5);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 69, 6);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 69, 8);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 69, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 70, 8);
INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 70, 9);
INSERT INTO tbl_cupo VALUES (null, 1,1, CURRENT_DATE, CURRENT_DATE, 70, 10);

INSERT INTO tbl_cupo VALUES (null, 2,2, CURRENT_DATE, CURRENT_DATE, 71, 5);

